const fs=require('fs'),vm=require('vm');
const src0=fs.readFileSync('app.js','utf8'); const cut=src0.indexOf('window.openAddGame='); if(cut<0)throw Error('exports not found');
let src=src0.slice(0,cut); const data={players:JSON.parse(fs.readFileSync('data/players.json')).players,maps:JSON.parse(fs.readFileSync('data/maps.json')).maps,matches:JSON.parse(fs.readFileSync('data/matches.json')).matches,aliases:JSON.parse(fs.readFileSync('data/aliases.json')).aliases};
src=src.replace("const DB={players:[],maps:[],matches:[],aliases:{}};",`const DB=${JSON.stringify(data)};`);
const els=new Map();const el=id=>{if(!els.has(id))els.set(id,{id,innerHTML:'',value:'',onclick:null,onchange:null,oninput:null,addEventListener(){},classList:{add(){},remove(){}}});return els.get(id)};
const document={querySelector(sel){return sel.startsWith('#')?el(sel.slice(1)):null},querySelectorAll(){return[{classList:{add(){},remove(){}}}]},body:{insertAdjacentHTML(){}},getElementById(id){return el(id)},createElement(){return{classList:{add(){},remove(){}},style:{}}}};
const ctx={console,Math,Date,JSON,Set,Map,Blob:class{},clearTimeout(){},setTimeout(){return 1},URL:{createObjectURL(){return'blob:'},revokeObjectURL(){}},document,localStorage:{getItem:()=>null,setItem:()=>{},removeItem:()=>{}}};ctx.window={CS5_EMBEDDED_DATA:{}};
vm.createContext(ctx);vm.runInContext(src,ctx);
const bad=[];
function check(name,fn){try{fn()}catch(e){bad.push({name,error:e.message})}}
check('map-select',()=>{ctx.maps(el('view'));const names=vm.runInContext("[...new Set(DB.maps.filter(m=>m.archived!==true).map(m=>m.map))]",ctx);const target=names.find(x=>x!=='mirage');el('mapSelect').value=target;el('mapSelect').onchange({target:el('mapSelect')});if(vm.runInContext('state.map',ctx)!==target)throw Error('selected map did not persist')});
check('map-player-focus',()=>{ctx.renderMapLab('dust2');const pid=vm.runInContext('state.mapPlayer',ctx);if(!pid)throw Error('no selected map player');el('mapPlayerFilter').value=pid;el('mapPlayerFilter').onchange({target:el('mapPlayerFilter')});if(vm.runInContext('state.mapPlayer',ctx)!==pid)throw Error('player focus did not persist')});
check('map-all-players-no-auto-focus',()=>{ctx.renderMapLab('dust2');el('mapPlayerFilter').value='all';el('mapPlayerFilter').onchange({target:el('mapPlayerFilter')});if(vm.runInContext('state.mapPlayer',ctx)!=='all')throw Error('all players did not persist');if(el('mapLab').innerHTML.includes('ВЫБРАННЫЙ ИГРОК</span><h3>дядя'))throw Error('all players unexpectedly focused a player')});
check('records-map-filter',()=>{ctx.records(el('view'));el('recordMap').value='dust2';el('recordMap').onchange({target:el('recordMap')});if(vm.runInContext("state.recordFilter+'|'+state.recordMap",ctx)!=='map|dust2')throw Error('map filter did not activate')});
check('records-bo3-filter',()=>{el('recordFilter').value='bo3';el('recordFilter').onchange({target:el('recordFilter')});if(vm.runInContext('state.recordFilter',ctx)!=='bo3')throw Error('BO3 filter did not persist')});
check('teams-empty-slots',()=>{vm.runInContext('state.teamA=[];state.teamB=[]',ctx);ctx.teams(el('view'));const a=vm.runInContext('state.teamA.length',ctx),b=vm.runInContext('state.teamB.length',ctx);if(a!==0||b!==0)throw Error('teams auto-filled unexpectedly')});
check('team-roster-drag',()=>{const pid=vm.runInContext('DB.players[0].player_id',ctx);ctx.dragRoster({dataTransfer:{setData(k,v){this.v=v},effectAllowed:''}},pid);const ev={preventDefault(){},dataTransfer:{getData(){return JSON.stringify({id:pid,t:'ROSTER'})}}};ctx.dropTeam(ev,'A');if(!vm.runInContext('state.teamA.includes('+JSON.stringify(pid)+')',ctx))throw Error('roster drag did not add player')});
check('team-empty-slot-drag',()=>{const pid=vm.runInContext('DB.players[1].player_id',ctx); const ev={preventDefault(){},dataTransfer:{getData(){return JSON.stringify({id:pid,t:'ROSTER'})}}};ctx.dropTeamSlot(ev,'B',0);if(!vm.runInContext('state.teamB.includes('+JSON.stringify(pid)+')',ctx))throw Error('empty slot drag did not add player: '+vm.runInContext('JSON.stringify(state.teamB)',ctx))});

check('maps-all-filter',()=>{ctx.maps(el('view'));el('mapSelect').value='all';el('mapSelect').onchange({target:el('mapSelect')});if(vm.runInContext('state.map',ctx)!=='all')throw Error('all maps selection did not persist');ctx.renderMapLab('all');if(!el('mapLab').innerHTML.includes('ВСЕ КАРТЫ'))throw Error('all maps lab not rendered')});
check('base-full-count',()=>{ctx.base(el('view'));const n=vm.runInContext('activeMatches().length',ctx);if(n!==32)throw Error('expected 32 active matches, got '+n);if(!el('view').innerHTML.includes('32'))throw Error('base count missing')});
check('base-series-sequential',()=>{vm.runInContext("state.baseMode='series'",ctx);ctx.base(el('view'));const html=el('view').innerHTML;if(!html.includes('СЕРИЯ 32')||!html.includes('СЕРИЯ 31')||!html.includes('match_063')||!html.includes('match_062'))throw Error('series display is not sequential 32..31 with compact IDs')});
check('bo3-detailed-series-aggregate',()=>{const rows=vm.runInContext('bo3RecordRows()',ctx);const r=rows.find(x=>x.matchId==='match_028'&&x.playerId==='donater');if(!r||r.k!==66||r.d!==35||r.a!==16)throw Error('donater match_028 BO3 aggregate is not 66/35/16: '+JSON.stringify(r))});
check('record-bo3-click-context',()=>{vm.runInContext("state.tab='records'",ctx);ctx.records(el('view'));el('recordFilter').value='bo3';el('recordFilter').onchange({target:el('recordFilter')});const html=el('view').innerHTML;if(!html.includes('СЕРИЯ'))throw Error('BO3 series context missing');if(!html.includes('openMatchDetail'))throw Error('BO3 rows do not open full lobby')});
check('trend-colors',()=>{const x=vm.runInContext("trendMarkup(2,'x')",ctx),y=vm.runInContext("trendMarkup(-2,'x')",ctx);if(!x.includes('trend-up')||!y.includes('trend-down'))throw Error('trend classes missing')});
console.log(JSON.stringify({PASS:bad.length===0,tests:['map-select','map-player-focus','records-map-filter','records-bo3-filter','teams-empty-slots','team-roster-drag','team-empty-slot-drag','trend-colors','map-all-players-no-auto-focus','base-series-sequential','bo3-detailed-series-aggregate'],bad},null,2));process.exitCode=bad.length?1:0;
