const fs=require('fs'),vm=require('vm');
const src0=fs.readFileSync('app.js','utf8');
const cut=src0.indexOf('window.openAddGame='); if(cut<0) throw Error('window exports not found');
let src=src0.slice(0,cut);
const data={players:JSON.parse(fs.readFileSync('data/players.json')).players,maps:JSON.parse(fs.readFileSync('data/maps.json')).maps,matches:JSON.parse(fs.readFileSync('data/matches.json')).matches,aliases:JSON.parse(fs.readFileSync('data/aliases.json')).aliases};
src=src.replace("const DB={players:[],maps:[],matches:[],aliases:{}};",`const DB=${JSON.stringify(data)};`);
const els=new Map(); const el=id=>{if(!els.has(id))els.set(id,{id,innerHTML:'',value:'',onclick:null,onchange:null,oninput:null,addEventListener(){},classList:{add(){},remove(){}}});return els.get(id)};
const document={querySelector(sel){return sel.startsWith('#')?el(sel.slice(1)):null},querySelectorAll(){return[{classList:{add(){},remove(){}}}]},body:{insertAdjacentHTML(){}},getElementById(id){return el(id)},createElement(){return{classList:{add(){},remove(){}},style:{}}}};
const ctx={console,Math,Date,JSON,Set,Map,Blob:class{},clearTimeout(){},setTimeout(){return 1},URL:{createObjectURL(){return'blob:'},revokeObjectURL(){}},document,localStorage:{getItem:()=>null,setItem:()=>{},removeItem:()=>{}}};ctx.window={CS5_EMBEDDED_DATA:{}};
vm.createContext(ctx);vm.runInContext(src,ctx);
const bad=[];
try{ctx.maps(el('view'));const names=vm.runInContext("[...new Set(DB.maps.filter(m=>m.archived!==true).map(m=>m.map))]",ctx);const target=names.find(x=>x!=='mirage');el('mapSelect').value=target;el('mapSelect').onchange({target:el('mapSelect')});if(vm.runInContext('state.map',ctx)!==target)bad.push({name:'map-select',error:'selected map did not persist'});}catch(e){bad.push({name:'map-select',error:e.message})}
try{ctx.records(el('view'));el('recordMap').value='dust2';el('recordMap').onchange({target:el('recordMap')});if(vm.runInContext("state.recordFilter+'|'+state.recordMap",ctx)!=='map|dust2')bad.push({name:'records-map-filter',error:'map filter did not activate'});el('recordMetric').value='deaths';el('recordMetric').onchange({target:el('recordMetric')});if(vm.runInContext('state.recordMetric',ctx)!=='deaths')bad.push({name:'records-metric',error:'metric filter did not persist'});}catch(e){bad.push({name:'records',error:e.message})}
try{ctx.teams(el('view'));const before=vm.runInContext('JSON.stringify([state.teamA,state.teamB])',ctx);const a=vm.runInContext('state.teamA[0]',ctx),b=vm.runInContext('state.teamB[0]',ctx);const ev={preventDefault(){},stopPropagation(){},dataTransfer:{getData(){return JSON.stringify({id:a,t:'A'})}}};ctx.dropTeamPlayer(ev,b,'B');const after=vm.runInContext('JSON.stringify([state.teamA,state.teamB])',ctx);if(before===after)bad.push({name:'team-drag-swap',error:'teams did not change'});if(!vm.runInContext('state.teamChange?.beforeA!=null',ctx))bad.push({name:'team-change-summary',error:'change summary missing'});}catch(e){bad.push({name:'team-drag-swap',error:e.message})}
console.log(JSON.stringify({PASS:bad.length===0,tests:['map-select','records-map-filter','records-metric','team-drag-swap','team-change-summary'],bad},null,2));process.exitCode=bad.length?1:0;
